### ISSUE TITLE
PELE executable, documents and data as flag

### ISSUE THREAD

**Issue by carlesperez94** [NostrumBioDiscovery/pele_platform#8]
It would be interesting to have a flag to set which PELE executable, documents and data folders do you want to use instead of having a hardcoded default.

Additionally, take into account that when using PELE > 1.6.1 you do not need to restrict the amount ligand rotamers because PELE will select a few of them randomly at each step.

**Comment by danielSoler93** [comment]
Pull request #9 fixes the issue. As you can now set the variable in the input.yml and will be send to Adaptive:

- pele_exec: "/home/..."
- pele_data:  "/Home/..."
- pele_documents:  "/home/.."

For more please check the updated docs. +

Thanks for the reminder of the rotamers I'll have that into account when PELE1.6.1 is in production

I close the issue. Re-open it if that does not work.

**Comment by carlesperez94** [comment]
Even though that I selected the version 1.6.1 of PELE, seems that it is taken the version 1.6.0 instead:

### YML file:
system: '4PP9_3MJ1.pdb'
pele_exec: '/gpfs/projects/bsc72/PELE++/mniv/**V1.6.1**/build/PELE-1.6.1_mpi'
pele_data: '/gpfs/projects/bsc72/PELE++/mniv/V1.6.1/Data'
pele_documents: '/gpfs/projects/bsc72/PELE++/mniv/V1.6.1/Documents'
working_folder: "CROSS_IFD"
log: false
chain: 'L'
resname: 'LIG'
adaptive_restart: false
seed: 12345
induced_fit: true
box_radius: 5
rmsd_pdb: '../../natives/3MJ1.pdb'
ca_constr: 1
cpus: 32
iterations: 1
steps: 250

### Output log:
"""
           PARAMS              

Restarting simulations True
Debug: False
Iterations: 1, Mpi processors: 32, Pele steps: 250
SpawningType: inverselyProportional
SimulationType: pele
Clustering method: rmsd
Output path:  output
Initial Structures:  [u'4PP9_3MJ1_processed.pdb']


Iteration 0
Production run...
mpirun -np 32 /gpfs/projects/bsc72/PELE++/mniv/V1.6.1/build/PELE-1.6.1_mpi tmp_output/controlFile0.conf
PELE version 1.6.0.${BUILD_TAG}
PELE (Protein Energy Landscape Exploration)

Copyright 2010-2017 BARCELONA SUPERCOMPUTING CENTER.

See the COPYRIGHT file at the top-level directory of this distribution.

Documents already created
Data already created
Data and Documents check completed...
validation: PASS
Running Controller!!
[Controller initialized] PELE version **1.6.0**.${BUILD_TAG}
"""
